#!/usr/bin/env bash
# Fetches MCP gateway secrets from 1Password and writes .env
# Prerequisites: op CLI installed and authenticated (op signin)
# Usage: ./1password-export.sh [vault-name]
#
# Expected 1Password vault structure (vault name defaults to "MCP Gateway"):
#   Item "Obsidian MCP"      → field: api_key, host, port
#   Item "Things 3 MCP"      → field: auth_token
#   Item "Slack MCP"         → field: bot_token, team_id
#   Item "GitHub MCP"        → field: personal_access_token
#   Item "Linear MCP"        → field: api_key
#   Item "Notion MCP"        → field: token
#   Item "Home Assistant MCP"→ field: url, token
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
VAULT="${1:-MCP Gateway}"

if ! command -v op &>/dev/null; then
  echo "Error: 1Password CLI (op) not found. Install from: https://developer.1password.com/docs/cli/"
  exit 1
fi

if ! op account list &>/dev/null; then
  echo "Error: Not signed in to 1Password. Run: op signin"
  exit 1
fi

echo "Fetching secrets from 1Password vault: ${VAULT}"

fetch() {
  local item="$1" field="$2" default="${3:-}"
  op item get "${item}" --vault "${VAULT}" --field "${field}" 2>/dev/null || echo "${default}"
}

cat > "${ENV_FILE}" <<EOF
# Auto-generated by 1password-export.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not commit this file — it contains secrets.

IMESSAGE_SCRIPT_PATH=/Users/ray.johnson/src/imessage-query-fastmcp-mcp-server/imessage-query-server.py

OBSIDIAN_API_KEY=$(fetch "Obsidian MCP" "api_key")
OBSIDIAN_HOST=$(fetch "Obsidian MCP" "host" "localhost")
OBSIDIAN_PORT=$(fetch "Obsidian MCP" "port" "27123")

THINGS3_AUTH_TOKEN=$(fetch "Things 3 MCP" "auth_token")

SLACK_BOT_TOKEN=$(fetch "Slack MCP" "bot_token" "xoxb-")
SLACK_TEAM_ID=$(fetch "Slack MCP" "team_id" "T")

GITHUB_PERSONAL_ACCESS_TOKEN=$(fetch "GitHub MCP" "personal_access_token" "ghp_")

LINEAR_API_KEY=$(fetch "Linear MCP" "api_key")

NOTION_TOKEN=$(fetch "Notion MCP" "token" "ntn_")

HOMEASSISTANT_URL=$(fetch "Home Assistant MCP" "url" "http://homeassistant.local:8123")
HOMEASSISTANT_TOKEN=$(fetch "Home Assistant MCP" "token")
EOF

echo "Written to ${ENV_FILE}"
echo ""
echo "Review for any blanks, then run ./start.sh"
