#!/usr/bin/env bash
# Fetches MCP gateway secrets from 1Password and writes .env
# Prerequisites: op CLI installed and authenticated (op signin)
# Usage: ./1password-export.sh [vault-name]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"
VAULT="${1:-MCP Gateway}"

if ! command -v op &>/dev/null; then
  echo "Error: 1Password CLI (op) not found. Install from: https://developer.1password.com/docs/cli/"
  exit 1
fi

if ! op account list &>/dev/null; then
  echo "Error: Not signed in to 1Password. Run: op signin"
  exit 1
fi

echo "Fetching secrets from 1Password vault: ${VAULT}"

fetch() {
  local item="$1" field="$2"
  op item get "${item}" --vault "${VAULT}" --field "${field}" 2>/dev/null || echo ""
}

cat > "${ENV_FILE}" <<EOF
# Auto-generated by 1password-export.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not commit this file — it contains secrets.

IMESSAGE_DB=~/Library/Messages/chat.db
OBSIDIAN_VAULT_PATH=$(fetch "Obsidian" "vault_path")
THINGS3_AUTH_TOKEN=$(fetch "Things 3" "auth_token")
SLACK_BOT_TOKEN=$(fetch "Slack MCP" "bot_token")
SLACK_TEAM_ID=$(fetch "Slack MCP" "team_id")
GITHUB_PERSONAL_ACCESS_TOKEN=$(fetch "GitHub MCP" "personal_access_token")
LINEAR_API_KEY=$(fetch "Linear MCP" "api_key")
NOTION_TOKEN=$(fetch "Notion MCP" "token")
EOF

echo "Written to ${ENV_FILE}"
echo ""
echo "Review the file and fill in any blank values, then run ./start.sh"
